// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9YOK7kZO_xHLgJmkvxsegSjkq7pDOWUs',
    appId: '1:7442963705:web:c285d2b7d3618cce2c5628',
    messagingSenderId: '7442963705',
    projectId: 'loginauthentication-a2b5b',
    authDomain: 'loginauthentication-a2b5b.firebaseapp.com',
    storageBucket: 'loginauthentication-a2b5b.appspot.com',
    measurementId: 'G-E5MC10C7N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD60VcSsx_wGi_xwLeRdE4FHDXU8XGq2Ws',
    appId: '1:7442963705:android:7a97799985b5ea142c5628',
    messagingSenderId: '7442963705',
    projectId: 'loginauthentication-a2b5b',
    storageBucket: 'loginauthentication-a2b5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9vGj1j5QzlT_GRqgCprBxp82tYAw7Xtc',
    appId: '1:7442963705:ios:da8e11060dfb6de62c5628',
    messagingSenderId: '7442963705',
    projectId: 'loginauthentication-a2b5b',
    storageBucket: 'loginauthentication-a2b5b.appspot.com',
    iosClientId: '7442963705-d1c126rga4ntnc99t014rlo5f67qcedd.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginStarbucks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9vGj1j5QzlT_GRqgCprBxp82tYAw7Xtc',
    appId: '1:7442963705:ios:fa0c55b2eb6d6e352c5628',
    messagingSenderId: '7442963705',
    projectId: 'loginauthentication-a2b5b',
    storageBucket: 'loginauthentication-a2b5b.appspot.com',
    iosClientId: '7442963705-movpltrth989jr12bsi6f2e4mhpq9rrp.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginStarbucks.RunnerTests',
  );
}
